// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "Shoppers",
    columns: [
      { name: "name", type: "text" },
      { name: "email", type: "text" },
      { name: "commission_scheme", type: "text" },
      { name: "active", type: "bool" },
    ],
    revLinks: [{ column: "shopper", table: "Sales" }],
  },
  {
    name: "Buyers",
    columns: [
      { name: "name", type: "text" },
      { name: "email", type: "text" },
      { name: "xero_contact_id", type: "text" },
    ],
    revLinks: [{ column: "buyer", table: "Sales" }],
  },
  {
    name: "Suppliers",
    columns: [
      { name: "name", type: "text" },
      { name: "email", type: "text" },
      { name: "xero_contact_id", type: "text" },
    ],
    revLinks: [{ column: "supplier", table: "Sales" }],
  },
  {
    name: "Introducers",
    columns: [
      { name: "name", type: "text" },
      { name: "commission_percent", type: "float" },
    ],
    revLinks: [{ column: "introducer", table: "Sales" }],
  },
  {
    name: "CommissionBands",
    columns: [
      { name: "band_type", type: "text" },
      { name: "min_threshold", type: "float" },
      { name: "max_threshold", type: "float" },
      { name: "commission_percent", type: "float" },
    ],
    revLinks: [{ column: "commission_band", table: "Sales" }],
  },
  {
    name: "Sales",
    columns: [
      { name: "sale_reference", type: "text" },
      { name: "sale_date", type: "datetime" },
      { name: "shopper", type: "link", link: { table: "Shoppers" } },
      { name: "buyer", type: "link", link: { table: "Buyers" } },
      { name: "supplier", type: "link", link: { table: "Suppliers" } },
      { name: "introducer", type: "link", link: { table: "Introducers" } },
      { name: "brand", type: "text" },
      { name: "category", type: "text" },
      { name: "item_title", type: "text" },
      { name: "quantity", type: "int" },
      { name: "sale_amount_inc_vat", type: "float" },
      { name: "currency", type: "text" },
      { name: "branding_theme", type: "text" },
      { name: "xero_invoice_number", type: "text" },
      { name: "xero_invoice_id", type: "text" },
      { name: "xero_invoice_url", type: "text" },
      { name: "invoice_status", type: "text" },
      { name: "invoice_paid_date", type: "datetime" },
      { name: "commission_locked", type: "bool" },
      { name: "commission_paid", type: "bool" },
      { name: "commission_lock_date", type: "datetime" },
      { name: "commission_paid_date", type: "datetime" },
      {
        name: "commission_band",
        type: "link",
        link: { table: "CommissionBands" },
      },
      { name: "internal_notes", type: "text" },
      { name: "sale_amount_ex_vat", type: "float" },
      { name: "buy_price", type: "float" },
      { name: "card_fees", type: "float" },
      { name: "shipping_cost", type: "float" },
      { name: "direct_costs", type: "float" },
      { name: "implied_shipping", type: "float" },
      { name: "gross_margin", type: "float" },
      { name: "commissionable_margin", type: "float" },
      { name: "status", type: "text" },
      { name: "error_flag", type: "bool" },
      { name: "error_message", type: "multiple" },
      { name: "commission_amount", type: "float" },
      { name: "commission_split_introducer", type: "float" },
      { name: "commission_split_shopper", type: "float" },
      { name: "introducer_share_percent", type: "float" },
      { name: "admin_override_commission_percent", type: "float" },
      { name: "admin_override_notes", type: "multiple" },
      { name: "xero_payment_date", type: "datetime" },
      { name: "buyer_type", type: "text" },
      { name: "needs_allocation", type: "bool", defaultValue: "false" },
      { name: "source", type: "text" },
      { name: "deleted_at", type: "datetime" },
      { name: "has_introducer", type: "bool", defaultValue: "false" },
      { name: "introducer_commission", type: "float" },
      { name: "is_payment_plan", type: "bool", defaultValue: "false" },
      { name: "payment_plan_instalments", type: "int" },
      { name: "commission_clawback", type: "bool" },
      { name: "commission_clawback_date", type: "datetime" },
      { name: "commission_clawback_reason", type: "text" },
    ],
    revLinks: [
      { column: "sale", table: "Errors" },
      { column: "sale", table: "PaymentSchedule" },
    ],
  },
  {
    name: "Errors",
    columns: [
      { name: "sale", type: "link", link: { table: "Sales" } },
      { name: "severity", type: "text" },
      { name: "source", type: "text" },
      { name: "message", type: "multiple" },
      { name: "timestamp", type: "datetime" },
      { name: "resolved", type: "bool" },
      { name: "resolved_by", type: "text" },
    ],
  },
  {
    name: "legacy_suppliers",
    columns: [
      { name: "supplier_clean", type: "text" },
      { name: "raw_variants", type: "multiple" },
      { name: "requires_review", type: "bool" },
      { name: "reason", type: "text" },
      { name: "first_seen", type: "datetime" },
      { name: "last_seen", type: "datetime" },
      { name: "trade_count", type: "int" },
    ],
    revLinks: [{ column: "supplier_id", table: "legacy_trades" }],
  },
  {
    name: "legacy_clients",
    columns: [
      { name: "client_clean", type: "text" },
      { name: "raw_variants", type: "multiple" },
      { name: "client_status", type: "text" },
      { name: "first_seen", type: "datetime" },
      { name: "last_seen", type: "datetime" },
      { name: "trade_count", type: "int" },
      { name: "requires_review", type: "bool" },
    ],
    revLinks: [{ column: "client_id", table: "legacy_trades" }],
  },
  {
    name: "legacy_trades",
    columns: [
      { name: "trade_date", type: "datetime" },
      { name: "raw_client", type: "text" },
      { name: "raw_supplier", type: "text" },
      { name: "client_id", type: "link", link: { table: "legacy_clients" } },
      {
        name: "supplier_id",
        type: "link",
        link: { table: "legacy_suppliers" },
      },
      { name: "item", type: "text" },
      { name: "brand", type: "text" },
      { name: "category", type: "text" },
      { name: "source", type: "text" },
      { name: "buy_price", type: "float" },
      { name: "sell_price", type: "float" },
      { name: "margin", type: "float" },
      { name: "invoice_number", type: "text" },
      { name: "raw_row", type: "json" },
    ],
  },
  {
    name: "PaymentSchedule",
    columns: [
      { name: "sale", type: "link", link: { table: "Sales" } },
      { name: "instalment_number", type: "int" },
      { name: "due_date", type: "datetime" },
      { name: "amount", type: "float" },
      { name: "status", type: "text" },
      { name: "xero_invoice_id", type: "text" },
      { name: "xero_invoice_number", type: "text" },
      { name: "paid_date", type: "datetime" },
      { name: "notes", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Shoppers = InferredTypes["Shoppers"];
export type ShoppersRecord = Shoppers & XataRecord;

export type Buyers = InferredTypes["Buyers"];
export type BuyersRecord = Buyers & XataRecord;

export type Suppliers = InferredTypes["Suppliers"];
export type SuppliersRecord = Suppliers & XataRecord;

export type Introducers = InferredTypes["Introducers"];
export type IntroducersRecord = Introducers & XataRecord;

export type CommissionBands = InferredTypes["CommissionBands"];
export type CommissionBandsRecord = CommissionBands & XataRecord;

export type Sales = InferredTypes["Sales"];
export type SalesRecord = Sales & XataRecord;

export type Errors = InferredTypes["Errors"];
export type ErrorsRecord = Errors & XataRecord;

export type LegacySuppliers = InferredTypes["legacy_suppliers"];
export type LegacySuppliersRecord = LegacySuppliers & XataRecord;

export type LegacyClients = InferredTypes["legacy_clients"];
export type LegacyClientsRecord = LegacyClients & XataRecord;

export type LegacyTrades = InferredTypes["legacy_trades"];
export type LegacyTradesRecord = LegacyTrades & XataRecord;

export type PaymentSchedule = InferredTypes["PaymentSchedule"];
export type PaymentScheduleRecord = PaymentSchedule & XataRecord;

export type DatabaseSchema = {
  Shoppers: ShoppersRecord;
  Buyers: BuyersRecord;
  Suppliers: SuppliersRecord;
  Introducers: IntroducersRecord;
  CommissionBands: CommissionBandsRecord;
  Sales: SalesRecord;
  Errors: ErrorsRecord;
  legacy_suppliers: LegacySuppliersRecord;
  legacy_clients: LegacyClientsRecord;
  legacy_trades: LegacyTradesRecord;
  PaymentSchedule: PaymentScheduleRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Oliver-Timmerman-s-workspace-d3730u.eu-central-1.xata.sh/db/Club19SalesOS",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
